### ISSUE TITLE
Loot Items not displaying 

### ISSUE THREAD

**Issue by Scabbrox** [sawprogramming/WoW-Raid-Manager#50]
Hi there.  Thanks for updating this for BfA.

I'm having some issues with the loot display in both front and back-end.  The plug-in is pulling the loot from the game and creating a list of names, dates and presumably items though the latter does not display in item column in either front end or admin side.

If I create a back-up and then open the loot csv file in excel the items are there, but they don't display on my website.

I tried turning the plug-in on and off, but nothing changed.

Thanks for any help you can provide.

**Comment by Scabbrox** [comment]
Some images to show what I mean.

Front end:

![screenshot 2018-12-24 at 11 12 13](https://user-images.githubusercontent.com/35002130/50396852-d866f800-076c-11e9-86e6-87fbe48a48fd.png)

Back end:
![screenshot 2018-12-24 at 11 12 29](https://user-images.githubusercontent.com/35002130/50396863-ea489b00-076c-11e9-8f0b-7e9617fe2765.png)

csv file:

![screenshot 2018-12-24 at 11 14 27](https://user-images.githubusercontent.com/35002130/50396907-19f7a300-076d-11e9-9bea-e55e7dfb0224.png)

**Comment by sawprogramming** [comment]
Thanks for the detailed report! Perhaps wowhead changed how they display loot links, I'm looking into it now.

**Comment by sawprogramming** [comment]
Committed a change that should fix this (it's working on my local machine). I'll push a build after I've looked into the other issues

**Comment by Scabbrox** [comment]
Thanks for the quick reply and quick update.

Will look out for it later.

**Comment by Scabbrox** [comment]
> Committed a change that should fix this (it's working on my local machine). I'll push a build after I've looked into the other issues

Just a confirmation that this still isn't working in your latest update.  In fact since I applied the update it's not added any new loot either which was working before, just not showing the item.

**Comment by RaefWolfe** [comment]
Congratulations on your wedding! Thank you for all the updates :)

Since the update yesterday I've gotten a few loot entries to display...but it's only for 2 characters and it's not even all of their loot (not even close).

https://www.ministryofdefense.net/raiding/raid-attendance/

Would be happy to provide any additional information you need.

**Comment by Scabbrox** [comment]
Yeah, not working for me either.  No difference with new patch, no loot showing since 23rd December 2018.

**Comment by sawprogramming** [comment]
I just figured this out; it's something to do with the new Blizzard API and the certificate used to host it. I just added the fix to my local. Sorry for not testing earlier! Thought no error logs meant it was working, but I was wrong!

**Comment by RaefWolfe** [comment]
It's working for me now! Awesome job :)

**Comment by Scabbrox** [comment]
I really wish I could say the same, it's just not working for me.

I'll be honest, it never really has worked as expected, the loot module only seemed to work for a period during and nothing I've been able to do since has ever fixed it.

I'm going to delete the entire thing, files and all as I can only think there is some sort of corruption that stops the files being updated.

If a complete reinstall doesn't work then I'm just going to stop bothering you and do without the plugin.

A couple of points I will mention though incase you want to look into them:

1.  When you upload the plugin into wordpress if you have an old version, then it'll fail and you have to delete it before you can install.  It gives an error that it is already installed otherwise, even though the version numbers are different.
2.  After installing if you click 'Activate' on the post install window it fails to activate and gives "invalid header found" as an error.  You need to go out of this window and into installed plugins and then click activate there to get it to activate.
3.  When adding players to the roster it doesn't recognise accents and will only add a player if you use the name without accents (e.g. to add Razáel I have to write Razael) but if there are two players called Razael of the same class on the same server you can't add either of them.  I have been unable to add our Monk Sòmi in any way because of this.

Any ideas why it's simply not working for me?

Lastly, Crucible of Storms was released two weeks ago and isn't in the raid list.

**Comment by RaefWolfe** [comment]
For what it's worth...

1&2, I've never had this issue, but I install via FTP and simply copy the files over manually. Do you use the wordpress interface?

3, I haven't had this issue either. I have both an Übernuts and a Çameltoetem in my roster.

If you haven't, try deactivating the plugin before adding new files. I have to deactivate & reactivate when I make changes, even via FTP, for them to take hold.

Crucible of Storms is a bit weird...it's not a "true" raid tier, it's a bonus raid. Adding it would mean that all raid runs (including Dazar'alor, which is still active until the next true raid releases) would be counted under CoS dates. Unless the dashboard / date picker had a way to select "this is a BfD raid" and "this is a CoS raid".

**Comment by RaefWolfe** [comment]
Looks like I spoke too soon about those special characters. I added them fine months ago, but when I try to edit them (because the portraits for them are among some of the broken) I can't save them.

**Comment by Scabbrox** [comment]
Yeah the accent issue is a new issue, it used to work in the working versions of last year.

Yes, I use the dashboard and Plugin menu, not ftp to manage all my plugins.  I hadn't tried deactiavting and reactivating after chnages but as I have now nuked the install I'll just try on a rebuild.

I did however download a back-up of the date before uninstalling with wipe data on.

**Comment by sawprogramming** [comment]
I'll look into fixing the accent issue this weekend hopefully, as well as seeing if the raid tier should be added.

As for the install process, I too just completely replace the files. I'd say the process to update would be:
1. Deactivate the plugin (don't drop tables on uninstall)
2. Delete the plugin
3. Add the plugin
4. Go back to the plugin page to activate

I can look into this too this weekend to see if there is an issue somewhere on a normal install process like that. 

I appreciate all the reports and useful info you give me!

**Comment by RaefWolfe** [comment]
Accented characters still an issue - trying to add new raiders for this tier, as well as edit old ones.

Also need to add Eternal Palace, which released on July 9, and is a 'true' raid tier.

**Comment by sawprogramming** [comment]
Simple fix for both, sorry it took so long to get to. Give the new build a try.

**Comment by RaefWolfe** [comment]
Seems to work well for me! Hopefully Scabbrox is still watching the thread and gives it a try.

**Comment by Scabbrox** [comment]
I've reinstalled it and will let you know if it works for me.

**Comment by Scabbrox** [comment]
Still not getting any loot showing.  Not sure how to force it to update but not seeing any change for me sadly.
